=== EroJMP/scholarship-system-XML-to-HTML-AJAX/administration/admin/xsd/application-academic.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           elementFormDefault="qualified"
           vc:minVersion="1.1">

  <xs:element name="applications">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="application" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="academic" type="academicType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
            <xs:assert test="if (@category = 'academic') then every $a in academic/personal_info/application_category satisfies $a = 'Academic Scholarship' else true()"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="academicType">
    <xs:sequence>
      <xs:element name="personal_info" type="personalInfoType"/>
      <xs:element name="address_information" type="addressInfoType"/>
      <xs:element name="school_information" type="schoolInfoType"/>
      <xs:element name="family_information" type="familyInfoType"/>
      <xs:element name="educational_information" type="educationalInfoType"/>
      <xs:element name="requirements" type="requirementsType"/>
      <xs:element name="date_submitted" type="xs:date"/>
      <xs:element name="reviewed_by" type="xs:string"/>
      <xs:element name="date_reviewed" type="xs:date"/>
      <xs:element name="status" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personalInfoType">
    <xs:sequence>
      <xs:element name="application_category" type="xs:string"/>
      <xs:element name="applicant_id" type="xs:string"/>
      <xs:element name="affiliation" type="xs:string"/>
      <xs:element name="type_of_id" type="xs:string"/>
      <xs:element name="id_number" type="xs:string"/>
      <xs:element name="gwa" type="xs:decimal"/>
      <xs:element name="last_name" type="xs:string"/>
      <xs:element name="middle_name" type="xs:string"/>
      <xs:element name="first_name" type="xs:string"/>
      <xs:element name="gender" type="xs:string"/>
      <xs:element name="date_of_birth" type="xs:date"/>
      <xs:element name="place_of_birth" type="xs:string"/>
      <xs:element name="age" type="xs:integer"/>
      <xs:element name="religion" type="xs:string"/>
      <xs:element name="civil_status" type="xs:string"/>
      <xs:element name="mobile_number" type="xs:string"/>
      <xs:element name="email_address" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="addressInfoType">
    <xs:sequence>
      <xs:element name="unit_number" type="xs:string"/>
      <xs:element name="house_number" type="xs:string"/>
      <xs:element name="street_name" type="xs:string"/>
      <xs:element name="barangay" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="schoolInfoType">
    <xs:sequence>
      <xs:element name="school_year" type="xs:string"/>
      <xs:element name="semester" type="xs:string"/>
      <xs:element name="name_of_school" type="xs:string"/>
      <xs:element name="school_address" type="xs:string"/>
      <xs:element name="school_type" type="xs:string"/>
      <xs:element name="academic_grade_level" type="xs:string"/>
      <xs:element name="academic_level" type="xs:string"/>
      <xs:element name="course" type="xs:string"/>
      <xs:element name="expected_date_of_grad" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="familyInfoType">
    <xs:sequence>
      <xs:element name="family" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="fam_id" type="xs:integer"/>
            <xs:element name="relation" type="xs:string"/>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="middle_name" type="xs:string"/>
            <xs:element name="last_name" type="xs:string"/>
            <xs:element name="occupation" type="xs:string"/>
            <xs:element name="monthly_income" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="combined_monthly_income" type="xs:decimal"/>
    </xs:sequence>
  </xs:complexType>

  <!-- education info -->
  <xs:complexType name="educationalInfoType">
    <xs:sequence>
      <xs:element name="education" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="educ_id" type="xs:integer"/>
            <xs:element name="academic_level_type" type="xs:string"/>
            <xs:element name="name_of_school" type="xs:string"/>
            <xs:element name="inclusive_years" type="xs:string"/>
            <xs:element name="honors_and_awards" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- requirements -->
  <xs:complexType name="requirementsType">
    <xs:sequence>
      <xs:element name="requirement" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="requirement_id" type="xs:integer"/>
            <xs:element name="requirement_name" type="xs:string"/>
            <xs:element name="attachment" type="xs:string"/>
          </xs:sequence>
          <xs:assert test="matches(attachment, '\.png$')"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== EroJMP/scholarship-system-XML-to-HTML-AJAX/administration/admin/xml/application-academic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE applications SYSTEM "../dtd/application-academic.dtd">
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/application-academic.xsd">
    <application category="academic">
        <academic>
            <personal_info>
                <application_category>Academic Scholarship</application_category>
                <applicant_id>2025001</applicant_id>
                <affiliation>New</affiliation>
                <type_of_id>Student ID</type_of_id>
                <id_number>UOE123456</id_number>
                <gwa>1.25</gwa>
                <last_name>Jarius</last_name>
                <middle_name>Amar</middle_name>
                <first_name>Pineda</first_name>
                <gender>Female</gender>
                <date_of_birth>2003-05-15</date_of_birth>
                <place_of_birth>Pasig City</place_of_birth>
                <age>22</age>g
                <religion>Roman Catholic</religion>
                <civil_status>Single</civil_status>
                <mobile_number>09171234567</mobile_number>
                <email_address>jane.doe@example.com</email_address>
            </personal_info>
            <address_information>
                <unit_number>962</unit_number>
                <house_number>962</house_number>
                <street_name>Labanos</street_name>
                <barangay>Manggahan</barangay>
            </address_information>
            <school_information>
                <school_year>2024-2025</school_year>
                <semester>1st Semester</semester>
                <name_of_school>New</name_of_school>
                <school_address>123 University Ave, Example City</school_address>
                <school_type>Private</school_type>
                <academic_grade_level>3rd Year</academic_grade_level>
                <academic_level>College</academic_level>
                <course>BS in Computer Science</course>
                <expected_date_of_grad>2025-05-15</expected_date_of_grad>
            </school_information>
            <family_information>
                <family>
                    <fam_id>1</fam_id>
                    <relation>Father</relation>
                    <first_name>John</first_name>
                    <middle_name>Michael</middle_name>
                    <last_name>Doe</last_name>
                    <occupation>Engineer</occupation>
                    <monthly_income>40000</monthly_income>
                </family>
                <family>
                    <fam_id>2</fam_id>
                    <relation>Mother</relation>
                    <first_name>Maricel</first_name>
                    <middle_name>Amar</middle_name>
                    <last_name>Pineda</last_name>
                    <occupation>BusinessWoman</occupation>
                    <monthly_income>40000</monthly_income>
                </family>
                <combined_monthly_income>70000</combined_monthly_income>
            </family_information>
            <educational_information>
                <education>
                    <educ_id>1</educ_id>
                    <academic_level_type>Senior High School</academic_level_type>
                    <name_of_school>Example Senior High</name_of_school>
                    <inclusive_years>2019-2021</inclusive_years>
                    <honors_and_awards>With High Honors</honors_and_awards>
                </education>
            </educational_information>
            <requirements>
                <requirement>
                    <requirement_id>1</requirement_id>
                    <requirement_name>Essay</requirement_name>
                    <attachment>essay.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>2</requirement_id>
                    <requirement_name>Interview Intake Form</requirement_name>
                    <attachment>interview_form.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>3</requirement_id>
                    <requirement_name>Barangay Certification of Residency</requirement_name>
                    <attachment>barangay_cert.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>4</requirement_id>
                    <requirement_name>Front of Valid ID</requirement_name>
                    <attachment>id_front..png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>5</requirement_id>
                    <requirement_name>Back of Valid ID</requirement_name>
                    <attachment>id_back..png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>6</requirement_id>
                    <requirement_name>Report Card</requirement_name>
                    <attachment>report_card.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>7</requirement_id>
                    <requirement_name>Proof of Enrollment</requirement_name>
                    <attachment>enrollment_proof.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>8</requirement_id>
                    <requirement_name>1x1 Photo</requirement_name>
                    <attachment>photo_1x1..png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>9</requirement_id>
                    <requirement_name>Proof of Income</requirement_name>
                    <attachment>income_proof.png</attachment>
                </requirement>
                <requirement>
                    <requirement_id>10</requirement_id>
                    <requirement_name>Application Form - Academic</requirement_name>
                    <attachment>application_form.png</attachment>
                </requirement>
            </requirements>
            <date_submitted>2025-03-15</date_submitted>
            <reviewed_by>Jarius Maui Pineda</reviewed_by>
            <date_reviewed>2025-04-02</date_reviewed>
            <status>Approved</status>
        </academic>
        <academic>
            <personal_info>
                <application_category>Academic Scholarship</application_category>
                <applicant_id>2025002</applicant_id>
                <affiliation>Old</affiliation>
                <type_of_id>School ID</type_of_id>
                <id_number>NIT987654</id_number>
                <gwa>1.10</gwa>
                <last_name>Santos</last_name>
                <middle_name>Gomez</middle_name>
                <first_name>Angela</first_name>
                <gender>Female</gender>
                <date_of_birth>2004-02-22</date_of_birth>
                <place_of_birth>Quezon City</place_of_birth>
                <age>21</age>
                <religion>Christian</religion>
                <civil_status>Single</civil_status>
                <mobile_number>09175551234</mobile_number>
                <email_address>angela.santos@nit.edu.ph</email_address>
            </personal_info>
            <address_information>
                <unit_number>15-B</unit_number>
                <house_number>789</house_number>
                <street_name>Sampaguita St</street_name>
                <barangay>San Antonio</barangay>
            </address_information>
            <school_information>
                <school_year>2024-2025</school_year>
                <semester>2nd Semester</semester>
                <name_of_school>National Institute of Technology</name_of_school>
                <school_address>456 Tech Park, Pasig City</school_address>
                <school_type>Public</school_type>
                <academic_grade_level>4th Year</academic_grade_level>
                <academic_level>College</academic_level>
                <course>BS in Information Technology</course>
                <expected_date_of_grad>2025-04-30</expected_date_of_grad>
            </school_information>
            <family_information>
                <family>
                    <fam_id>1</fam_id>
                    <relation>Father</relation>
                    <first_name>Carlos</first_name>
                    <middle_name>Villanueva</middle_name>
                    <last_name>Santos</last_name>
                    <occupation>Driver</occupation>
                    <monthly_income>18000</monthly_income>
                </family>
                <family>
                    <fam_id>2</fam_id>
                    <relation>Mother</relation>
                    <first_name>Luz</first_name>
                    <middle_name>Cruz</middle_name>
                    <last_name>Santos</last_name>
                    <occupation>Housewife</occupation>
                    <monthly_income>0</monthly_income>
                </family>
                <combined_monthly_income>18000</combined_monthly_income>
            </family_information>
            <educational_information>
                <education>
                    <educ_id>1</educ_id>
                    <academic_level_type>Elementary</academic_level_type>
                    <name_of_school>Pasig Central Elementary School</name_of_school>
                    <inclusive_years>2018-2020</inclusive_years>
                    <honors_and_awards>N/A</honors_and_awards>
                </education>
                <education>
                    <educ_id>2</educ_id>
                    <academic_level_type>Junior High School</academic_level_type>
                    <name_of_school>Sagad High School</name_of_school>
                    <inclusive_years>2018-2020</inclusive_years>
                    <honors_and_awards>With Honors</honors_and_awards>
                </education>
                <education>
