=== EroJMP/scholarship-system-XML-to-HTML-AJAX/user/dtd/user-login.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (first_name, last_name, birthday, gender, email, mobile_number, password)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mobile_number (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== EroJMP/scholarship-system-XML-to-HTML-AJAX/user/xml/user-login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "../dtd/user-login.dtd">
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/user-login.xsd">
  <user>
    <first_name>Demo</first_name>
    <last_name>Student</last_name>
    <birthday>2004-06-15</birthday>
    <gender>Male</gender>
    <email>student@plpasig.edu.ph</email>
    <mobile_number>09171234567</mobile_number>
    <password>e8302be67ed93e969d1d21ccbe5445ffe4cf59ce079dde7060093ccf38151668</password> <!-- Student#2025 -->
  </user>
</users>
