=== EroJMP/scholarship-system-XML-to-HTML-AJAX/administration/admin/dtd/application-sk.dtd
<!ELEMENT applications (application+)>
<!ELEMENT application (category, (academic | college_honor_graduates | bar_and_board | private | out_of_school_learners | sk_officials | chip_in | sports))>
<!ATTLIST application category IDREF #IMPLIED>

<!ELEMENT sk_officials (personal_info, address_information?, school_information?, family_information?, educational_information?, requirements, date_submitted, reviewed_by, date_reviewed, status)>

<!ELEMENT personal_info (application_category, applicant_id, affiliation?, type_of_id?, id_number?, gwa?, last_name, middle_name?, first_name, gender, date_of_birth, place_of_birth, age, religion, civil_status, mobile_number, email_address)>
<!ELEMENT address_information (unit_number, house_number, street_name, barangay)>
<!ELEMENT school_information (school_year, semester, name_of_school, school_address, school_type, academic_grade_level?, academic_level?, course?, expected_date_of_grad?)>
<!ELEMENT family_information (family+, combined_monthly_income)>
<!ELEMENT family (fam_id, relation, first_name, middle_name, last_name, occupation, monthly_income)>
<!ELEMENT educational_information (education+)>
<!ELEMENT education (educ_id, academic_level_type, name_of_school, inclusive_years, honors_and_awards)>
<!ELEMENT requirements (requirement+)>
<!ELEMENT requirement (requirement_id, requirement_name, attachment)>

<!ELEMENT application_category (#PCDATA)>
<!ELEMENT applicant_id (#PCDATA)>
<!ELEMENT affiliation (#PCDATA)>
<!ELEMENT type_of_id (#PCDATA)>
<!ELEMENT id_number (#PCDATA)>
<!ELEMENT gwa (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!ELEMENT place_of_birth (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT religion (#PCDATA)>
<!ELEMENT civil_status (#PCDATA)>
<!ELEMENT mobile_number (#PCDATA)>
<!ELEMENT email_address (#PCDATA)>
<!ELEMENT unit_number (#PCDATA)>
<!ELEMENT house_number (#PCDATA)>
<!ELEMENT street_name (#PCDATA)>
<!ELEMENT barangay (#PCDATA)>
<!ELEMENT school_year (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT name_of_school (#PCDATA)>
<!ELEMENT school_address (#PCDATA)>
<!ELEMENT school_type (#PCDATA)>
<!ELEMENT academic_grade_level (#PCDATA)>
<!ELEMENT academic_level (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT expected_date_of_grad (#PCDATA)>
<!ELEMENT fam_id (#PCDATA)>
<!ELEMENT relation (#PCDATA)>
<!ELEMENT occupation (#PCDATA)>
<!ELEMENT monthly_income (#PCDATA)>
<!ELEMENT combined_monthly_income (#PCDATA)>
<!ELEMENT educ_id (#PCDATA)>
<!ELEMENT academic_level_type (#PCDATA)>
<!ELEMENT inclusive_years (#PCDATA)>
<!ELEMENT honors_and_awards (#PCDATA)>
<!ELEMENT requirement_id (#PCDATA)>
<!ELEMENT requirement_name (#PCDATA)>
<!ELEMENT attachment (#PCDATA)>
<!ELEMENT date_submitted (#PCDATA)>
<!ELEMENT reviewed_by (#PCDATA)>
<!ELEMENT date_reviewed (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== EroJMP/scholarship-system-XML-to-HTML-AJAX/administration/admin/xml/application-sk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE applications SYSTEM "../dtd/application-sk.dtd">
<applications>
    <application category="sk_officials">
        <sk_officials>
            <personal_info>
                <application_category>SK Scholarship</application_category>
                <applicant_id>SK-0001</applicant_id>
                <affiliation>New</affiliation>
                <type_of_id>School ID</type_of_id>
                <id_number>ESU7891011</id_number>
                <gwa>1.50</gwa>
                <last_name>Pineda</last_name>
                <middle_name>Garcia</middle_name>
                <first_name>Jarius Maui</first_name>
                <gender>Male</gender>
                <date_of_birth>2004-02-28</date_of_birth>
                <place_of_birth>Quezon City</place_of_birth>
                <age>21</age>
                <religion>Christian</religion>
                <civil_status>Single</civil_status>
                <mobile_number>09181234567</mobile_number>
                <email_address>rafael.lopez@example.com</email_address>
            </personal_info>
            <address_information>
                <unit_number>24B</unit_number>
                <house_number>1378</house_number>
                <street_name>Camia Street</street_name>
                <barangay>San Roque</barangay>
            </address_information>
            <school_information>
                <school_year>2024-2025</school_year>
                <semester>1st Semester</semester>
                <name_of_school>Ace International University</name_of_school>
                <school_address>456 Kapasigan Blvd, Pasig City</school_address>
                <school_type>Public</school_type>
                <academic_grade_level>2nd Year</academic_grade_level>
                <academic_level>College</academic_level>
                <course>BA Psychology</course>
                <expected_date_of_grad>2025-04-30</expected_date_of_grad>
            </school_information>
            <family_information>
                <family>
                    <fam_id>1</fam_id>
                    <relation>Father</relation>
                    <first_name>Carlos</first_name>
                    <middle_name>Domingo</middle_name>
                    <last_name>Lopez</last_name>
                    <occupation>Driver</occupation>
                    <monthly_income>20000</monthly_income>
                </family>
                <family>
                    <fam_id>2</fam_id>
                    <relation>Mother</relation>
                    <first_name>Lucia</first_name>
                    <middle_name>Reyes</middle_name>
                    <last_name>Lopez</last_name>
                    <occupation>Vendor</occupation>
                    <monthly_income>18000</monthly_income>
                </family>
                <combined_monthly_income>38000</combined_monthly_income>
            </family_information>
            <educational_information>
                <education>
                    <educ_id>1</educ_id>
                    <academic_level_type>Elementary</academic_level_type>
                    <name_of_school>Pasig City Elementary School</name_of_school>
                    <inclusive_years>2009-2013</inclusive_years>
                    <honors_and_awards>With Honors</honors_and_awards>
                </education>
                <education>
                    <educ_id>2</educ_id>
                    <academic_level_type>Junior High School</academic_level_type>
                    <name_of_school>Pasig City High School</name_of_school>
                    <inclusive_years>2013-2017</inclusive_years>
                    <honors_and_awards>With High Honors</honors_and_awards>
                </education>
                <education>
                    <educ_id>3</educ_id>
                    <academic_level_type>Senior High School</academic_level_type>
                    <name_of_school>Pasig City High School</name_of_school>
                    <inclusive_years>2017-2019</inclusive_years>
                    <honors_and_awards>With Honors</honors_and_awards>
                </education>
                <education>
                    <educ_id>4</educ_id>
                    <academic_level_type>College</academic_level_type>
                    <name_of_school>Ace International University</name_of_school>
                    <inclusive_years>2019-2025</inclusive_years>
                    <honors_and_awards>With Honors</honors_and_awards>
                </education>
            </educational_information>
            <requirements>
                <requirement>
                    <requirement_id>1</requirement_id>
                    <requirement_name>Essay</requirement_name>
                    <attachment>lopez_essay.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>2</requirement_id>
                    <requirement_name>Interview Intake Form</requirement_name>
                    <attachment>intake_form.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>3</requirement_id>
                    <requirement_name>Barangay Certification of Residency</requirement_name>
                    <attachment>cert_residency.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>4</requirement_id>
                    <requirement_name>Front of Valid ID</requirement_name>
                    <attachment>front_id.jpg</attachment>
                </requirement>
                <requirement>
                    <requirement_id>5</requirement_id>
                    <requirement_name>Back of Valid ID</requirement_name>
                    <attachment>back_id.jpg</attachment>
                </requirement>
                <requirement>
                    <requirement_id>6</requirement_id>
                    <requirement_name>Report Card</requirement_name>
                    <attachment>report_card_rafael.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>7</requirement_id>
                    <requirement_name>Proof of Enrollment</requirement_name>
                    <attachment>enrollment_rafael.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>8</requirement_id>
                    <requirement_name>1x1 Photo</requirement_name>
                    <attachment>photo_1x1_rafael.jpg</attachment>
                </requirement>
                <requirement>
                    <requirement_id>9</requirement_id>
                    <requirement_name>Proof of Income</requirement_name>
                    <attachment>income_doc.pdf</attachment>
                </requirement>
                <requirement>
                    <requirement_id>10</requirement_id>
                    <requirement_name>Application Form - Academic</requirement_name>
                    <attachment>academic_form_rafael.pdf</attachment>
                </requirement>
            </requirements>
            <date_submitted>2025-04-02</date_submitted>
            <reviewed_by>Nicia Perez</reviewed_by>
            <date_reviewed>2025-04-22</date_reviewed>
            <status>Approved</status>
        </sk_officials>
        <sk_officials>
            <personal_info>
                <application_category>SK Scholarship</application_category>
                <applicant_id>SK-0002</applicant_id>
                <affiliation>New</affiliation>
                <type_of_id>School ID</type_of_id>
                <id_number>PASIG7890012</id_number>
                <gwa>1.75</gwa>
                <last_name>Castro</last_name>
                <middle_name>Salazar</middle_name>
                <first_name>Ana Maria</first_name>
                <gender>Female</gender>
                <date_of_birth>2003-08-14</date_of_birth>
                <place_of_birth>Pasig City</place_of_birth>
                <age>22</age>
                <religion>Roman Catholic</religion>
                <civil_status>Single</civil_status>
                <mobile_number>09281234567</mobile_number>
                <email_address>ana.castro@example.com</email_address>
            </personal_info>
            <address_information>
                <unit_number>17C</unit_number>
                <house_number>1425</house_number>
                <street_name>P. Oliveros St.</street_name>
                <barangay>Barangay Palatiw</barangay>
            </address_information>
            <school_information>
                <school_year>2024-2025</school_year>
                <semester>1st Semester</semester>
                <name_of_school>University of Pasig</name_of_school>
                <school_address>Edsa Extension, Pasig City</school_address>
                <school_type>Private</school_type>
                <academic_grade_level>3rd Year</academic_grade_level>
                <academic_level>College</academic_level>
                <course>Bachelor of Science in Business Administration</course>
                <expected_date_of_grad>2025-04-30</expected_date_of_grad>
            </school_information>
            <family_information>
                <family>
                    <fam_id>1</fam_id>
                    <relation>Father</relation>
                    <first_name>Antonio</first_name>
                    <middle_name>Reyes</middle_name>
                    <last_name>Castro</last_name>
                    <occupation>Construction Worker</occupation>
                    <monthly_income>25000</monthly_income>
                </family>
                <family>
                    <fam_id>2</fam_id>
                    <relation>Mother</relation>
                    <first_name>Maria</first_name>
                    <middle_name>Luisa</middle_name>
